openapi: 3.0.0
info:
  title: Motion Detection API
  description: API for retrieving motion detection data.
  version: 1.0.0
servers:
  - url: https://open-meteo.com/en/docs/historical-weather-api#latitude=15.5&longitude=101&timezone=Asia%2FBangkok
paths:
  /motion:
    get:
      summary: Get all motion detection data
      operationId: getMotionData
      responses:
        '200':
          description: A list of motion detection data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MotionData'
    post:
      summary: Insert a new motion detection data
      operationId: insertMotionData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMotionData'
      responses:
        '200':
          description: Successfully inserted
        '400':
          description: Bad request
  /motion/{id}:
    get:
      summary: Get motion detection data by ID
      operationId: getMotionDataById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Motion detection data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MotionData'
        '404':
          description: Motion detection data not found
    delete:
      summary: Delete motion detection data by ID
      operationId: deleteMotionData
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully deleted
        '404':
          description: Motion detection data not found
components:
  schemas:
    MotionData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ts:
          type: string
          format: date-time
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
        temp:
          type: number
          format: float
        sensor:
          type: integer
    NewMotionData:
      type: object
      properties:
        ts:
          type: string
          format: date-time
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
        temp:
          type: number
          format: float
        sensor:
          type: integer
